### ISSUE TITLE
Allows upload of files that are not images

### ISSUE THREAD

**Issue by vaneshsu99** [KSJI/alpha#14]
I uploaded an excel file as a picture of my meal and it was accepted.

Reproduction steps:
1. Click on upload a new post 
2. Click on the choose file button
3. Click on a file that is not an image (I chose an excel file)

<img width="1274" alt="screen shot 2018-06-03 at 9 53 07 pm" src="https://user-images.githubusercontent.com/26750673/40898877-b3c2dd46-6778-11e8-964f-fa1972664a3a.png">

**Comment by Kyle-Simpson** [comment]
Fixed in 1.1
