### ISSUE TITLE
Uncaught error in console, unable to submit

### ISSUE THREAD

**Issue by johnwjlim** [KSJI/alpha#16]
1) Upload a new post
2) Enter title
3) Submit

![image](https://user-images.githubusercontent.com/34074206/40903383-09a2d0fa-678c-11e8-890c-da728a441b39.png)

**Comment by juan3674-1532739** [comment]
This is not a bug. I think the reason that it did not allow to submit was that you did not upload any images yet, which is what we intended to do. We only allow users to skip the part that we say "optional"
