### ISSUE TITLE
cannot create an account

### ISSUE THREAD

**Issue by harrybarng** [KSJI/alpha#17]
i used: KDNJF#UBN3liub(*Prp98h9*DHSF(*hp98h4p98h3unkafsd65f653ds13541sd351f3sd5f43853a153rfsefjjhbskeryuai7v9i7vfihvdsfhLIY#LHBRLIUGI&EHI*YRELILIUHELIUSGLFIUHSEFIUHLIUhiuhig97987y*&I&^%T&I^%*^%&^R*E&^TF&^TESZ^&TGF&I^R&^T@&^R(O^#Fo8yfg3o86g8^FG#O8fgO#&*^T*&TYO*&T#*F7tgO#&G*
on name, email, username, and password. It would not let me create the account (Cannot press create account)

![image](https://user-images.githubusercontent.com/37923379/40904760-946b1022-6790-11e8-9dd5-ecb4d600deaa.png)

**Comment by juan3674-1532739** [comment]
this is not a bug. The reason that it did not allow to create an account was that it was not valid email form. Like ____@___.com
