### ISSUE TITLE
after signing up, my information is not saved

### ISSUE THREAD

**Issue by harrybarng** [KSJI/alpha#18]
I signed up with 
![image](https://user-images.githubusercontent.com/37923379/40904864-fd774982-6790-11e8-9b8a-a9ce85814a56.png)
password was also 789

after getting redirected to home page, I clicked on settings icon but it gave me this

![image](https://user-images.githubusercontent.com/37923379/40904894-1817459e-6791-11e8-9727-47fca15d5fc8.png)

**Comment by MirelesI** [comment]
I was able to find the cause of the problem, as you should not have been allowed to make a password 3 characters long, you're information wasn't saving but still let you in the site first try but not afterwards. Thank you.
