### ISSUE TITLE
Buttons don't work unless clicking on the text.

### ISSUE THREAD

**Issue by aqt21** [KSJI/alpha#2]
Buttons do not work if not clicking directly on the labels for the button even though it seems that the buttons extend much further.

Reproduction Steps:
(Log-In Button)
1. Visit the website login page
2. Type in your credentials for an account you've made to ensure it's not because of wrong credentials
3. Click in the whitespace in the button that says "Log In"
4. Button event will not occur

(Create-An-Account Button)
1. Visit the website login page
2. Click the Sign-Up Hyperlink
3. Type in all credentials in the form to ensure that it's not because of wrong credentials
4. Click in the whitespace in the button that says "Create-An-Account"
5. Button event will not occur

(Terms-And-Conditions Button)
1. Visit the website login page
2. Click the Sign-Up Hyperlink
3. Type in all credentials in the form to ensure that it's not because of wrong credentials
4. Click the text that says "Create-An-Account"
5. Click the check box accepting the terms and conditions
6. Click the white space around in the button labeled "Continue"
7. Button event will not occur

**Comment by Kyle-Simpson** [comment]
Fixed in 1.1
