### ISSUE TITLE
Entering an invalid email asks me for current password and deletes all my posts

### ISSUE THREAD

**Issue by janequichocho** [KSJI/alpha#20]
When I enter an invalid email in the settings section, I'm asked to provide my current password and when I do, I'm redirected to the home page and all my previous uploads are gone.

Reproduction steps:
1. Upload a new post.
2. Click on settings icon
3. Enter in random characters in email address text field that do not make up a valid email address
4. Click on save
5. Provide current password when prompted

**Comment by Kyle-Simpson** [comment]
Fixed in 1.1
