### ISSUE TITLE
Overflowing input completely breaks the website

### ISSUE THREAD

**Issue by harrybarng** [KSJI/alpha#21]
I inputted 3333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333

in the expense boxes and this happened: https://drive.google.com/open?id=1R6mqKJREGNH0DIsaJ_QCTCM1u54KQ6qT

**Comment by abegel** [comment]
@harrybarng Was this a real bug or an accidental bug report?

**Comment by harrybarng** [comment]
this was for cash management group; not this group
