### ISSUE TITLE
Can create multiple accounts with the same email and information

### ISSUE THREAD

**Issue by sunwookang** [KSJI/alpha#22]
I created an account with the following information:
- Full name: Sunwoo Kang
- Email: sunwoo@uw.edu
- Weight: 150lbs
- Username: aybqii
- Password: 1234567890

I replicated the same information and it sent me to the terms and conditions page again. I was logged in correctly as sunwoo@uw.edu again. I also replicated it again while using a different password and it worked.

![2018-06-04](https://user-images.githubusercontent.com/29963756/40945002-c276ee20-680b-11e8-8d50-a23dbe3dd58d.png)

**Comment by MirelesI** [comment]
I was able to find the cause of the problem! Thank you!
