### ISSUE TITLE
Delete Icon Very Small on Individual Post Page

### ISSUE THREAD

**Issue by lisakoss** [KSJI/alpha#23]
After creating a new post and clicking on the post from the home page to view more details, the trash can icon for the delete a post functionality is really small. This happens when I first view the page on the web using Firefox.

[minor]

<img width="1440" alt="screen shot 2018-06-04 at 3 35 17 pm" src="https://user-images.githubusercontent.com/22549728/40945308-1322a340-680d-11e8-9f6a-447c1891e6ee.png">

If I convert my screensize to iPhone 6S, I still have the same problem.

<img width="438" alt="screen shot 2018-06-04 at 3 36 10 pm" src="https://user-images.githubusercontent.com/22549728/40945327-2dea1c80-680d-11e8-9aed-467b181be82c.png">

Although, if I convert my screen back to web size, I can then see the trash can icon at it's full size. Converting back to iPhone 6S also still allows me to see the trash can icon.

<img width="1440" alt="screen shot 2018-06-04 at 3 36 18 pm" src="https://user-images.githubusercontent.com/22549728/40945347-45a1792c-680d-11e8-982c-62717168cc2b.png">
<img width="1440" alt="screen shot 2018-06-04 at 3 36 20 pm" src="https://user-images.githubusercontent.com/22549728/40945350-47101c32-680d-11e8-8e20-cedc255bddb7.png">

Also despite the fact that I am unable to see the icon at it's full size in the first two screenshots, I am able to still click on it.

**Comment by juan3674-1532739** [comment]
We acknowledge this issue. Since we did not use at media in css but used percent to display the icon, it is causing the issue that you have. But, we are not currently considering the specific size of the screen. We are mostly working on just desktop size. So, currently, this issue is not an issue.
