### ISSUE TITLE
Submit Meal Don't Submit

### ISSUE THREAD

**Issue by PhillipYPark** [KSJI/alpha#3]
<img width="531" alt="screen shot 2018-06-03 at 5 38 28 pm" src="https://user-images.githubusercontent.com/19401335/40893136-f637ce3a-6754-11e8-9cfb-00d7809f3687.png">
Entered input of meal and uploaded a picture but does not submit.
Submit button should redirect back to homepage. 
Cancel button works.

**Comment by Kyle-Simpson** [comment]
So the API we're using takes about 3 seconds to process the colors, so with a few seconds of patience, the image will process and then be entered into our database.
