### ISSUE TITLE
Users can successfully create an account with a password that only has 3 characters, but it does not allow users to log in with that information

### ISSUE THREAD

**Issue by Jingwnpn** [KSJI/alpha#7]
I created an account with password '123'. I was able to create the account successfully with that password, but when I tried to sign in with the account, it did not give me any response/error message after clicking the LOG-IN button multiple times. I was unable to log in with my account that has password '123'

**Comment by MirelesI** [comment]
I was able to fix this as it wasn't creating it successfully but rather letting you through that one time and not saving that account or creating it at all. Thank you.
